services:
  - type: web
    name: tesla-stok-takip
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 100 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 